//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRUEBA_CLIENTES1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\USUARIO1\\\\Documents\\\\BD\\\\SAE70EMPRE01.FDB")]
        public string bDLan1 {
            get {
                return ((string)(this["bDLan1"]));
            }
            set {
                this["bDLan1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\USUARIO1\\\\Documents\\\\BD\\\\SAE70EMPRE02.FDB")]
        public string bDFerre {
            get {
                return ((string)(this["bDFerre"]));
            }
            set {
                this["bDFerre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\USUARIO1\\\\Documents\\\\BD\\\\SAE70EMPRE03.FDB")]
        public string bDLlantasM {
            get {
                return ((string)(this["bDLlantasM"]));
            }
            set {
                this["bDLlantasM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\USUARIO1\\\\Documents\\\\BD\\\\SAE70EMPRE04.FDB")]
        public string bDLlantasE {
            get {
                return ((string)(this["bDLlantasE"]));
            }
            set {
                this["bDLlantasE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\USUARIO1\\\\Documents\\\\BD\\\\SAE70EMPRE05.FDB")]
        public string bDLlantasP {
            get {
                return ((string)(this["bDLlantasP"]));
            }
            set {
                this["bDLlantasP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Null")]
        public string empresaEnUso {
            get {
                return ((string)(this["empresaEnUso"]));
            }
            set {
                this["empresaEnUso"] = value;
            }
        }
    }
}
